### ISSUE TITLE
Cannot upload asset because it is too large

### ISSUE THREAD

**Issue by S-Dafarra** [dic-iit/ify-dependencies-vcpkg#7]
After 3 long hours, the upload of the assets for the new release (https://github.com/dic-iit/ify-dependencies-vcpkg/releases/tag/v0.4.0) failed because the file size is too large. See https://pipelines.actions.githubusercontent.com/VkArbTmOcLJAO2C018bn6we12UHCWlAM5DwPqLGrTkMB1F89lA/_apis/pipelines/1/runs/60/signedlogcontent/4?urlExpires=2020-06-12T10%3A23%3A38.2977877Z&urlSigningMethod=HMACV1&urlSignature=xUTMUH8KYJxGpYgr4UrCeAoSS2Lk30kFd5siFts24xs%3D

How can we proceed? @traversaro

**Comment by traversaro** [comment]
Indeed the max size of GitHub releases is 2 GB (see https://help.github.com/en/github/managing-large-files/distributing-large-binaries), and for some reason the `qt5-tools` port is making the archive reach ~2.9 Gb from the existing ~0.5 Gb (See https://github.com/dic-iit/ify-dependencies-vcpkg/releases/tag/v0.3.0).

A way of reducing the size of the vcpkg archive (but I do not know if it will be effective, as the 2.9 GB size is fishy  anyway) is to  delete the `.pdb`  files from the directories `vcpkg/installed/x64-windows/bin` and  `vcpkg/installed/x64-windows/debug/bin`. These files are just debug symbols and source that simplify debugging, but given that we are using Windows just for deployment we can remove them.

**Comment by traversaro** [comment]
In the  meanwhile, I started building `qt5-tools` locally to understand how it is possible that it is so large.

**Comment by S-Dafarra** [comment]
The weird thing is that the required component, ``Qt Linguist`` is supposed to be pretty small, while ``qt-tools`` includes other tools that are not necessary.

**Comment by S-Dafarra** [comment]
Maybe we can create two different packages :thinking:

**Comment by S-Dafarra** [comment]
I tried to replicate this on Windows. After downloading the dependencies, the ``vcpkg`` folder was weighing around 50GB. More than 40 were restored after deleting the ``buildtrees``, ``packages`` and ``downloads`` folder. Now it weighs ~10GB. This is the space distribution:
![image](https://user-images.githubusercontent.com/18591940/84588819-bbbff380-ae2a-11ea-97a9-dbbfe711c8a4.png)

**Comment by traversaro** [comment]
Ah fak, I think I know what is going on. The tools itself are compiled with static qt, so each tool will weight a lot. As if I understood correctly we just need some CMake functions (but I may be wrong) probably we can remove most of the tools that are unused after the qt5-tools port has been installed, and then after this cleanup compress the archive. Obviously it would be ideal to first check if compilation is working correctly while deleting, to avoid accidentally deleting useful files.

**Comment by S-Dafarra** [comment]
> Ah fak, I think I know what is going on. The tools itself are compiled with static qt, so each tool will weight a lot. As if I understood correctly we just need some CMake functions (but I may be wrong) probably we can remove most of the tools that are unused after the qt5-tools port has been installed, and then after this cleanup compress the archive. Obviously it would be ideal to first check if compilation is working correctly while deleting, to avoid accidentally deleting useful files.

I guess that those CMake functions call tools like ``lupdate`` and ``lrelease``, but yes, with some iterations it may be possible to nail down the tools that are actually useful.

**Comment by S-Dafarra** [comment]
By further checking, around 5GB are in the folder ``qt5/debug/bin``. In addition, there is something I do not understand. The executables of ``Qt Linguist``, ``lupdate`` and ``lrelease`` are both in the folder ``qt5/bin`` and ``qt5-tools/bin`` 🤔

**Comment by traversaro** [comment]
> By further checking, around 5GB are in the folder `qt5/debug/bin`.

Where is that directory located? Why it is not shown in https://github.com/dic-iit/ify-dependencies-vcpkg/issues/7#issuecomment-643736195 ? What does it contain?

> In addition, there is something I do not understand. The executables of Qt Linguist, lupdate and lrelease are both in the folder qt5/bin and qt5-tools/bin 🤔

This seem  a vcpkg port bug.

**Comment by S-Dafarra** [comment]
> Where is that directory located? Why it is not shown in #7 (comment) ? What does it contain?

In the tools directory. Here I am expanding that folder
![image](https://user-images.githubusercontent.com/18591940/84629880-554eda00-aeeb-11ea-903c-bedafed4063d.png)

> This seem a vcpkg port bug.

I checked, and those files were not there in the zip file without ``qt5-tools``.

**Comment by traversaro** [comment]
Most of the files seems to be `.pdb` , that should not there in the tools folder and can be safely removed.

**Comment by GiulioRomualdi** [comment]
Can we avoid to compile the libraries in debug? Probably we can reduce the amount of storage (and time) required

**Comment by S-Dafarra** [comment]
For reference, this is the content of ``Qt5LinguistToolsConfig.cmake``
```cmake

if (CMAKE_VERSION VERSION_LESS 2.8.3)
    message(FATAL_ERROR "Qt 5 requires at least CMake version 2.8.3")
endif()

get_filename_component(_qt5_linguisttools_install_prefix "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

macro(_qt5_LinguistTools_check_file_exists file)
    if(NOT EXISTS "${file}" )
        message(FATAL_ERROR "The package \"Qt5LinguistTools\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
endmacro()

if (NOT TARGET Qt5::lrelease)
    add_executable(Qt5::lrelease IMPORTED)

    set(imported_location "${_qt5_linguisttools_install_prefix}/tools/qt5-tools/bin/lrelease.exe")
    _qt5_LinguistTools_check_file_exists(${imported_location})

    set_target_properties(Qt5::lrelease PROPERTIES
        IMPORTED_LOCATION ${imported_location}
    )
endif()

if (NOT TARGET Qt5::lupdate)
    add_executable(Qt5::lupdate IMPORTED)

    set(imported_location "${_qt5_linguisttools_install_prefix}/tools/qt5-tools/bin/lupdate.exe")
    _qt5_LinguistTools_check_file_exists(${imported_location})

    set_target_properties(Qt5::lupdate PROPERTIES
        IMPORTED_LOCATION ${imported_location}
    )
endif()

if (NOT TARGET Qt5::lconvert)
    add_executable(Qt5::lconvert IMPORTED)

    set(imported_location "${_qt5_linguisttools_install_prefix}/tools/qt5-tools/bin/lconvert.exe")
    _qt5_LinguistTools_check_file_exists(${imported_location})

    set_target_properties(Qt5::lconvert PROPERTIES
        IMPORTED_LOCATION ${imported_location}
    )
endif()

set(Qt5_LRELEASE_EXECUTABLE Qt5::lrelease)
set(Qt5_LUPDATE_EXECUTABLE Qt5::lupdate)

include("${CMAKE_CURRENT_LIST_DIR}/Qt5LinguistToolsMacros.cmake")
```
So, in the end, only those three executables are needed. I would add also ``Linguist.exe`` such that it is possible for people to modify the translations. If there are still problem of size, a strong cut may be an option 🤔

**Comment by S-Dafarra** [comment]
Finally: https://github.com/dic-iit/ify-dependencies-vcpkg/releases/tag/v0.4.0 :tada: Closing this
